#!/usr/bin/env python3

import argparse
import lights
from devices import Devices as d
from scenes import Scenes as s

lights = lights.Lights

# Create the parser
description = "Control LifX devices and settings via the CLI."
epilog      = ""
job_options = argparse.ArgumentParser(description=description, epilog=epilog)

# Add the arguments
job_options.add_argument('-d',
                         '--devices',
                         default = False,
                         action  = 'store_true',
                         help    = 'List LifX devices.')
job_options.add_argument('-t',
                         '--toggle',
                         default = False,
                         action  = 'store',
                         help    = 'Toggle the specified light.')
job_options.add_argument('-s',
                         '--scenes',
                         default = False,
                         action  = 'store_true',
                         help    = 'List LifX scenes.')
job_options.add_argument('-a',
                         '--activate',
                         default = False,
                         action  = 'store',
                         help    = 'Activate LifX scene.')

args     = job_options.parse_args()
devices  = args.devices
toggle   = args.toggle
scenes   = args.scenes
scene_id = args.activate

if devices:
    d.get()
if scenes:
    s.get()

if toggle:
    lights.toggle(toggle) 
if scene_id:
    s.activate(scene_id)
